<!-- R Commander Markdown Template -->

Replace with Main Title
=======================

### Your Name

### `r as.character(Sys.Date())`

```{r echo=FALSE}
# include this code chunk as-is to set options
knitr::opts_chunk$set(comment=NA, prompt=TRUE, out.width=750, fig.height=8, fig.width=8)
library(Rcmdr)
library(car)
library(RcmdrMisc)
```


```{r echo=FALSE}
# include this code chunk as-is to enable 3D graphs
library(rgl)
knitr::knit_hooks$set(webgl = hook_webgl)
```


```{r}
load("C:/Users/crist/Desktop/Mat 3/PRACTICA 4/Mundo95.RData")
```


```{r}
Datos <- within(Datos, {
  ALFA_fac <- as.factor(alfabet)
})
```

```{r}
summary(Datos)
```


```{r}
library(abind, pos=21)
```


```{r}
library(e1071, pos=22)
```

```{r}
numSummary(Datos[,"alfabet", drop=FALSE], statistics=c("quantiles", "skewness", 
  "kurtosis"), quantiles=c(0,.25,.5,.75,1,.30), type="1")
```

```{r}
numSummary(Datos[,c("alfabet", "espvidaf"), drop=FALSE], statistics=c("quantiles", "cv"), 
  quantiles=c(0,.25,.5,.75,1,.30))
```

```{r}
Datos <- within(Datos, {
  urbana_rec <- Recode(urbana, 
  '0:25="[0,25]"; 25:50="(25,50]"; 50:75="(50,75]"; 75:100="(75,100]"; ; ;', as.factor=TRUE)
})
```

```{r}
local({
  .Table <- xtabs(~urbana_rec+región, data=Datos)
  cat("\nFrequency table:\n")
  print(.Table)
  cat("\nTotal percentages:\n")
  print(totPercents(.Table))
  .Test <- chisq.test(.Table, correct=FALSE)
  print(.Test)
})
```

```{r}
local({
  .Table <- xtabs(~región+urbana_rec, data=Datos)
  cat("\nFrequency table:\n")
  print(.Table)
  cat("\nTotal percentages:\n")
  print(totPercents(.Table))
  .Test <- chisq.test(.Table, correct=FALSE)
  print(.Test)
})
```

```{r}
Tapply(calorías ~ región + urbana_rec, mean, na.action=na.omit, data=Datos) 
  # mean by groups
```

```{r}
library(colorspace, pos=23)
```


```{r}
with(Datos, piechart(religión, xlab="", ylab="", main="religión", col=rainbow_hcl(11), 
  scale="percent"))
```

```{r}
local({
  .Table <- with(Datos, table(religión))
  cat("\ncounts:\n")
  print(.Table)
  cat("\npercentages:\n")
  print(round(100*.Table/sum(.Table), 2))
})
```

```{r}
with(Datos, Barplot(religión, xlab="religión", ylab="Frequency", label.bars=TRUE))
```

```{r}
with(Datos, Hist(urbana, groups=región, scale="percent", breaks="Sturges", col="darkgray"))
```


```{r}
with(Datos, Hist(urbana, groups=región, scale="percent", breaks=c(0,25,50,75,100), 
  col="darkgray"))
```


```{r}
Datos$Resta <- with(Datos, espvidaf-espvidam)
```

```{r}
Boxplot(Resta~región, data=Datos, id=list(method="y"))
```

```{r}
library(lattice, pos=24)
```


```{r}
xyplot(espvidaf ~ fertilid | región, type="p", pch=16, auto.key=list(border=TRUE), 
  par.settings=simpleTheme(pch=16), scales=list(x=list(relation='same'), 
  y=list(relation='same')), data=Datos)
```

